### ISSUE TITLE
LaTeX: normalfont command ignoring sans option

### ISSUE THREAD

**Issue by abhabongse** [tlwg/fonts-tlwg#1]
Dear maintainer,

I was using this LaTeX package while experiencing the following problem.
For example, if `\usepackage[sans,sflaksaman,rmnorasi]{fonts-tlwg}` is loaded with the specified option, the default font family should be sans-serif (as documented). However, consider the following code:
```latex
ประโยคภาษาไทย \normalfont ประโยคภาษาไทย
```
it yields the unexpected result
![image](https://cloud.githubusercontent.com/assets/6845502/25933902/77105670-35cf-11e7-83de-95f0e293fbe3.png)

This issue can be solved with a couple of lines fix. I will submit a pull request and hopefully will receive a kind response from you.

**Comment by thep** [comment]
Sorry for a late reply. I have retrieved the relevant patch from your pull request and will commit it soon with minor adjustment.

**Comment by thep** [comment]
Committed, with latex/examples/Makefile.am changed so that testsans.tex is included in "make dist" tarball, commented LaTeX code removed, and ChangeLog added.

Thank you for your work!
