### ISSUE TITLE
Windows 11 doesn't recognize Tlwg* OTF fonts as monospaced fonts

### ISSUE THREAD

**Issue by cwt** [tlwg/fonts-tlwg#14]
OS: Windows 11 23H2

I attempted to install the OTF version of the following Tlwg* fonts:

- Tlwg Mono
- Tlwg Typewriter
- Tlwg Typist
- Tlwg Typo

However, none of them were recognized as monospaced fonts. Consequently, I couldn't utilize any of them in Windows Terminal or other applications that require monospaced fonts, such as [gVim for Windows](https://github.com/vim/vim-win32-installer).

Subsequently, I uninstalled them and reinstalled them with the TTF version. This time, Windows recognized "Tlwg Mono" and "Tlwg Typo" as monospaced fonts, allowing me to use them in Windows Terminal and gVim.

**Comment by thep** [comment]
Thanks for the report. I managed to find a Windows 11 machine for testing, and the OTF versions of TlwgMono and TlwgTypo are recoginized by gVim as monospace fonts.
![20240325-gvim-tlwgtypo](https://github.com/tlwg/fonts-tlwg/assets/631551/3dfb98b0-7480-497e-9bf7-0b2251f39bd2)

**Comment by cwt** [comment]
@thep I try again after update Windows, and now the Windows recognize both `Tlwg Mono` and `Tlwg Typo` as monospaced fonts in both gvim and Windows Terminal.

So, it is likely to be a bug in Windows itself. I'm closing this issue now.

Thank you.
