### ISSUE TITLE
Garuda font: backquote glyph is very small

### ISSUE THREAD

**Issue by agguser** [tlwg/fonts-tlwg#4]
Try following text with Garuda font: 'ก', \`ก\`, "ก".

**Comment by abhabongse** [comment]
Do you have a minimal but complete `LaTeX` file to show such effect?

**Comment by agguser** [comment]
No, I just used a text editor, with the font. You can test it with above text, and note how small the backquote glyph.

**Comment by agguser** [comment]
Note: this problem occurs at font size of 10 or less.
![garuda](https://user-images.githubusercontent.com/1206106/34197155-c59bb438-e597-11e7-85c4-525208f0efac.png)

**Comment by abhabongse** [comment]
I cannot reproduce the effect you outlined. What specific editor did you use?

I’ve tried using **gedit** and I got the following:
> ![image](https://user-images.githubusercontent.com/6845502/34929955-7419799e-f9f9-11e7-9339-d0ff1a1e19e7.png)

In **LibreOffice Writer** I got:
> ![image](https://user-images.githubusercontent.com/6845502/34929974-906b4ae6-f9f9-11e7-8e1a-d0f0a13cee28.png)

In both cases, the backquotes seem to look comparable to straight single/double quotes, in my opinion.

**Comment by agguser** [comment]
All programs, including LibreOffice Writer. I use Arch Linux with `extra/fonts-tlwg 0.6.4-1` package.

Why your "Garuda 9" is larger than my "Garuda 10" (both characters and quotation marks) in the comment above?

(You may try "Garuda 7" or lower to see if the backquote looks uncomfortable compare to other characters.)

**Comment by thep** [comment]
The backquote (a.k.a. grave) glyph is intended to be of this size because it's Latin _grave accent_. It's also used in accented letters like à è ì ò ù À È Ì Ò Ù. This is also true for many other fonts. And I think the size is not too small for Garuda.

**Comment by agguser** [comment]
I found that setting fontconfig's `autohint` to true fixed it.
