### ISSUE TITLE
Bundling TrueType/OpenType fonts with LaTeX font package?

### ISSUE THREAD

**Issue by abhabongse** [tlwg/fonts-tlwg#6]
Is there a possibility to add TrueType/OpenType version of fonts with the LaTeX package `fonts-tlwg`?

I have seen this being done with other font packages such as 
- [opensans](https://www.ctan.org/tex-archive/fonts/opensans/fonts/truetype/public/opensans)
- [roboto](https://www.ctan.org/tex-archive/fonts/roboto/truetype)
- [lmodern](https://www.ctan.org/tex-archive/fonts/lm/fonts/opentype/public/lm)
- [droid](https://www.ctan.org/tex-archive/fonts/droid/fonts/truetype/public/droid)
- etc.

This will become especially useful for users of [ShareLaTeX](https://www.sharelatex.com/)/[Overleaf](https://www.overleaf.com/) as they will no longer be required to upload Thai fonts in order to use XeLaTeX. Are there a legal/philosophical reasons against this practice? Would it take a lot of time to achieve this packaging with CTAN?

Looking towards responses, and thanks for all hard work!

**Comment by thep** [comment]
Thank you for your suggestion. I certainly agree with providing it. Let me figure out how to do so.
