### ISSUE TITLE
Latex: ff missing when use laksaman font

### ISSUE THREAD

**Issue by santirak** [tlwg/fonts-tlwg#8]
The letter "ff" is missing when I use laksaman font in latex (latexmk). For example, the word "different" will become "dierent".

`\documentclass[a4paper]{article}
\usepackage[english,thai]{babel}
\usepackage[utf8x]{inputenc}
\usepackage{fonts-tlwg}
\begin{document}

	\usefont{LTH}{kinnari}{m}{n}
	different\\
	
	\usefont{LTH}{laksaman}{m}{n}
	different\\

\end{document}`

**Comment by thep** [comment]
I wonder which fonts-tlwg version you are using. This problem has been fixed since 0.6.5.

Please see this commit which dates more than a year:
https://github.com/tlwg/fonts-tlwg/commit/45faba800c613c993977d0c54a4eee63e75336da

**Comment by santirak** [comment]
Package: fonts-tlwg 2014/07/05 v1.1 Thai TLWG Fonts

**Comment by thep** [comment]
That's the version of `fonts-tlwg.sty`, not that of `fonts-tlwg` package itself.

I just realize that you may be using `fonts-tlwg` as a pre-installed package from some TeX distribution.

Another way is to check the font's version tag:

```
$ grep '^Version' `kpsewhich laksaman.afm`
Version 004.001
```

Or just find and open `laksaman.afm` in a text editor and search for the line beginning with `Version`.

**Comment by santirak** [comment]
Oh yes, I am using Version 003.011.

Thank you so much.

**Comment by thep** [comment]
Closing the old non-bug issue.
